### ISSUE TITLE
Move SQL queries to an external configuration file

### ISSUE THREAD

**Issue by Asitha** [wso2/ballerina-message-broker#520]
**Description:**

It's better to move out the SQL queries to an external configuration file. This way we can have the generic SQL queries as well as the DB specific queries in the configuration to gain performance improvements with DB specific syntaxes.

Suggested config file

```yaml
generic:
 contentRead: Select * FROM MB_CONTENT LIMIT 20

oracle:
 contentRead: Select * FROM MB_CONTENT WHERE ROWNUM < 20
```
In this config file, DB specific query should supercede the generic query. This can be resolved at broker startup. 

The relevant database type can be resolved using the JDBC URL. Here the relevant database tag can be mapped to the configuration file.

```url
catalog.url=database_tag\://host:port/

eg:
catalog.url=jdbc:weblogic:sqlserver://abc1.us.oracle.com\HITTEST: 1434;databaseName=ps3_8396
```
